// src/components/AppHeader.vue
<template>
  <header class="h-14 md:h-16 sticky top-0 z-30 flex items-center gap-2 px-3 md:px-4
    border-b border-gray-200 dark:border-gray-800 bg-white/70 dark:bg-gray-900/70 backdrop-blur
    text-gray-900 dark:text-gray-100">
    <button @click="ui.toggleSidebar()" class="md:hidden text-gray-700 dark:text-gray-300 hover:text-gray-900 dark:hover:text-white" :aria-label="ui.isSidebarOpen ? 'Close navigation' : 'Open navigation'">
      <svg v-if="!ui.isSidebarOpen" class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"/>
      </svg>
      <svg v-else class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/>
      </svg>
    </button>
    <div class="font-semibold text-gray-900 dark:text-white">Loke Cards</div>
    <nav aria-label="Breadcrumb" class="ml-2 hidden sm:block text-gray-600 dark:text-gray-400">...</nav>
    <div class="ml-auto flex items-center gap-2">
      <StatusPill state="synced"/>
      <ThemeToggle/>
    </div>
  </header>
</template>

<script setup>
import StatusPill from './StatusPill.vue';
import ThemeToggle from './ThemeToggle.vue';
import { useUiStore } from '../stores/ui';

const ui = useUiStore();
</script>

<style scoped>
/* Add any component specific styles here */
</style>

// shared/src/lib/components/AppHeader.svelte
<script lang="ts">
  import { toggleSidebar } from '../stores/ui.store';
  import StatusPill from './StatusPill.svelte';
  import NetworkToggle from './NetworkToggle.svelte';
  import ThemeToggle from './ThemeToggle.svelte';
  import ProjectPicker from './ProjectPicker.svelte';
  export let title: string = 'Loke Cards';
</script>

<header class="sticky top-0 z-30 flex items-center justify-between gap-3 px-4 py-2 border-b border-gray-200 dark:border-gray-700 bg-white/80 dark:bg-gray-900/80 backdrop-blur supports-[backdrop-filter]:bg-white/60 dark:supports-[backdrop-filter]:bg-gray-900/60">
  <button class="md:hidden p-2 rounded hover:bg-gray-100 dark:hover:bg-gray-800" aria-label="Toggle menu" on:click={toggleSidebar}>
    <!-- Burger icon -->
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6">
      <path fill-rule="evenodd" d="M3.75 5.25a.75.75 0 0 1 .75-.75h15a.75.75 0 0 1 0 1.5h-15a.75.75 0 0 1-.75-.75Zm0 6.75a.75.75 0 0 1 .75-.75h15a.75.75 0 0 1 0 1.5h-15a.75.75 0 0 1-.75-.75Zm0 6.75a.75.75 0 0 1 .75-.75h15a.75.75 0 0 1 0 1.5h-15a.75.75 0 0 1-.75-.75Z" clip-rule="evenodd" />
    </svg>
  </button>

  <h1 class="text-lg font-semibold text-gray-900 dark:text-gray-100">{title}</h1>
  <div class="ml-auto flex items-center gap-2">
    <StatusPill />
    <NetworkToggle />
    <ProjectPicker />
    <ThemeToggle />
  </div>
</header>
