// apps-vue/shared/src/components/AppSidebar.vue
<template>
  <div
    class="relative z-40 md:hidden"
    role="dialog"
    aria-modal="true"
    v-if="ui.isSidebarOpen"
  >
    <div
      class="fixed inset-0 bg-gray-600 bg-opacity-75 transition-opacity"
      @click="ui.closeSidebar()"
    ></div>

    <div class="fixed inset-0 flex z-40">
      <div
        class="relative flex-1 flex flex-col max-w-xs w-full bg-gray-50 dark:bg-gray-950"
      >
        <div class="absolute top-0 right-0 -mr-12 pt-2">
          <button
            type="button"
            class="ml-1 flex items-center justify-center h-10 w-10 rounded-full focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white"
            @click="ui.closeSidebar()"
          >
            <span class="sr-only">Close sidebar</span>
            <svg
              class="h-6 w-6 text-white"
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke-width="2"
              stroke="currentColor"
              aria-hidden="true"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M6 18L18 6M6 6l12 12"
              />
            </svg>
          </button>
        </div>

        <aside class="h-full overflow-auto p-3">
          <SidebarMenu />
        </aside>
      </div>
    </div>
  </div>

  <!-- Desktop Sidebar -->
  <aside
    class="h-full overflow-auto p-3 bg-gray-50 dark:bg-gray-950 block w-64 shrink-0 border-r border-gray-200 dark:border-gray-800 relative z-20"
  >
    <SidebarMenu />
  </aside>
</template>

<script setup>
import { useUiStore } from "../stores/ui";
import NavLink from "./NavLink.vue";
import SidebarMenu from "./SidebarMenu.vue";

const ui = useUiStore();
</script>

<style scoped>
/* Active link styling */
.nav-item.router-link-active {
  @apply bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-white;
}
</style>

// shared/src/lib/components/AppSidebar.svelte
<script>
  import { isSidebarOpen, closeSidebar } from '../stores/ui.store.js';
  import { onMount } from 'svelte';
  import SidebarMenu from './SidebarMenu.svelte';
  let open;
  const unsubscribe = isSidebarOpen.subscribe((v) => (open = v));
  onMount(() => () => unsubscribe());
  
</script>

<!-- Desktop sidebar -->
<aside class="hidden md:flex md:flex-col md:w-60 border-r border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900">
  <div class="p-3 text-sm text-gray-700 dark:text-gray-300">
    <SidebarMenu />
  </div>
  <div class="mt-auto p-3 text-xs text-gray-500">Sidebar</div>
  
</aside>

<!-- Mobile drawer overlay -->
{#if open}
  <div class="md:hidden fixed inset-0 z-40 bg-black/40" on:click={closeSidebar}></div>
  <aside class="md:hidden fixed z-50 inset-y-0 left-0 w-72 bg-white dark:bg-gray-900 border-r border-gray-200 dark:border-gray-700 p-3">
    <button class="mb-3 p-2 rounded hover:bg-gray-100 dark:hover:bg-gray-800" on:click={closeSidebar} aria-label="Close menu">Close</button>
    <div class="text-sm text-gray-700 dark:text-gray-300">
      <SidebarMenu />
    </div>
  </aside>
{/if}
