// apps-vue/shared/src/components/NetworkToggle.vue
<template>
  <button
    class="inline-flex items-center gap-1 text-sm px-3 py-1 rounded-full border transition-colors"
    :class="online ? 'bg-emerald-600 text-white border-emerald-700 hover:bg-emerald-700' : 'bg-gray-600 text-white border-gray-700 hover:bg-gray-700'"
    :aria-pressed="!online"
    @click="toggle()"
  >
    <span v-if="online">Online</span>
    <span v-else>Offline</span>
  </button>
</template>

<script setup>
import { computed, onMounted, onBeforeUnmount } from 'vue'
import { useSyncStore } from '../stores/syncStore'
import { setForceOffline } from '../api/client'

const sync = useSyncStore()

const online = computed(() => sync.status !== 'offline')

function apply(forceOffline) {
  setForceOffline(forceOffline)
  try { localStorage.setItem('LC_FORCE_OFFLINE', forceOffline ? '1' : '0') } catch (_) {}
  if (forceOffline) {
    sync.markOffline()
  } else {
    // If coming back online and there is nothing pending, mark as synced
    if (sync.pending > 0) sync.setStatus('idle')
    else sync.markSynced()
  }
}

function toggle() {
  apply(online.value) // if online -> force offline, else clear
}

function handleNavigatorOnline() {
  // Only auto-apply online if not manually forced offline
  apply(false)
}

function handleNavigatorOffline() {
  apply(true)
}

onMounted(() => {
  try {
    const persisted = localStorage.getItem('LC_FORCE_OFFLINE')
    if (persisted === '1') apply(true)
  } catch (_) {}
  window.addEventListener('online', handleNavigatorOnline)
  window.addEventListener('offline', handleNavigatorOffline)
})

onBeforeUnmount(() => {
  window.removeEventListener('online', handleNavigatorOnline)
  window.removeEventListener('offline', handleNavigatorOffline)
})
</script>

<style scoped>
</style>

// shared/src/lib/components/NetworkToggle.svelte
<script lang="ts">
  import { status, pending, markOffline, markSynced, setStatus } from '../stores/sync.store';
  import { get } from 'svelte/store';
  const online = () => get(status) !== 'offline';

  function apply(forceOffline) {
    try { localStorage.setItem('LC_FORCE_OFFLINE', forceOffline ? '1' : '0'); } catch {}
    if (forceOffline) {
      markOffline();
    } else {
      if (get(pending) > 0) setStatus('idle');
      else markSynced();
    }
  }
  const toggle = () => apply(online());
  const handleNavigatorOnline = () => apply(false);
  const handleNavigatorOffline = () => apply(true);

  if (typeof window !== 'undefined') {
    try { if (localStorage.getItem('LC_FORCE_OFFLINE') === '1') apply(true); } catch {}
    window.addEventListener('online', handleNavigatorOnline);
    window.addEventListener('offline', handleNavigatorOffline);
  }
</script>

<button
  class="inline-flex items-center gap-1 text-sm px-3 py-1 rounded-full border transition-colors"
  class:!bg-emerald-600={online()} class:!text-white={online()} class:!border-emerald-700={online()} class:hover:!bg-emerald-700={online()}
  class:bg-gray-600={!online()} class:text-white={!online()} class:border-gray-700={!online()} class:hover:bg-gray-700={!online()}
  aria-pressed={!online()}
  on:click={toggle}
>
  {#if online()} Online {:else} Offline {/if}
</button>
