// packages/ui/src/components/AppHeader.svelte
<script lang="ts">
  import { onDestroy } from 'svelte';
  import ProjectPicker from './ProjectPicker.svelte';
  import { currentProject } from '@loke/shared/stores/project.svelte';
  import { themePreference, type ThemePreference } from '../stores/theme';

  let {
    title = '',
    showProjectPicker = true,
    showThemeToggle = true,
  }: {
    title?: string;
    showProjectPicker?: boolean;
    showThemeToggle?: boolean;
  } = $props();

  const displayTitle = $derived(currentProject ? `${title}: ${currentProject.name}` : title);

  let theme = $state<ThemePreference>(themePreference.getCurrent());

  const stopThemeSubscription = themePreference.subscribe((value) => {
    theme = value;
  });

  onDestroy(() => {
    stopThemeSubscription();
  });

  function toggleTheme() {
    themePreference.toggle();
  }
</script>

<header class="bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 px-4 py-3">
  <div class="flex items-center justify-between gap-4">
    <!-- Title -->
    <h1 class="text-xl font-semibold text-gray-900 dark:text-gray-100">{displayTitle}</h1>

    <!-- Right side: Project Picker + Theme Toggle -->
    <div class="flex items-center gap-3">
      <!-- Project Picker -->
      {#if showProjectPicker}
        <ProjectPicker />
      {/if}

      <!-- Theme Toggle -->
      {#if showThemeToggle}
        <button
          type="button"
          class="rounded-lg bg-gray-100 p-2 transition-colors hover:bg-gray-200 dark:bg-gray-700 dark:hover:bg-gray-600"
          onclick={toggleTheme}
          title="Toggle theme (current: {theme})"
        >
          {#if theme === 'light'}
            <svg class="h-5 w-5 text-gray-700" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z"></path>
            </svg>
          {:else if theme === 'dark'}
            <svg class="h-5 w-5 text-gray-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z"></path>
            </svg>
          {:else}
            <svg class="h-5 w-5 text-gray-700 dark:text-gray-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"></path>
            </svg>
          {/if}
        </button>
      {/if}
    </div>
  </div>
</header>

// src/components/AppHeader.vue
<template>
  <header class="h-14 md:h-16 sticky top-0 z-30 flex items-center gap-2 px-3 md:px-4
    border-b border-gray-200 dark:border-gray-800 bg-white/70 dark:bg-gray-900/70 backdrop-blur
    text-gray-900 dark:text-gray-100">
    <button @click="ui.toggleSidebar()" class="md:hidden text-gray-700 dark:text-gray-300 hover:text-gray-900 dark:hover:text-white" :aria-label="ui.isSidebarOpen ? 'Close navigation' : 'Open navigation'">
      <svg v-if="!ui.isSidebarOpen" class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"/>
      </svg>
      <svg v-else class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/>
      </svg>
    </button>
    <div class="font-semibold text-gray-900 dark:text-white">Loke Cards</div>
    <nav aria-label="Breadcrumb" class="ml-2 hidden sm:block text-gray-600 dark:text-gray-400">...</nav>
    <div class="ml-auto flex items-center gap-2">
      <StatusPill state="synced"/>
      <ThemeToggle/>
    </div>
  </header>
</template>

<script setup>
import StatusPill from './StatusPill.vue';
import ThemeToggle from './ThemeToggle.vue';
import { useUiStore } from '../stores/ui';

const ui = useUiStore();
</script>

<style scoped>
/* Add any component specific styles here */
</style>
