// src/components/SceneIdInput.vue
<template>
  <div class="scene-id-input">
    <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
      Scene ID
      <span class="text-red-500">*</span>
    </label>
    <input
      :value="modelValue"
      @input="handleInput"
      @blur="handleBlur"
      type="text"
      placeholder="scene_forest_entrance"
      class="w-full px-3 py-2 border rounded-lg text-gray-900 dark:text-gray-100 bg-white dark:bg-gray-900 placeholder-gray-400 dark:placeholder-gray-600 focus:outline-none focus:ring-2 focus:ring-blue-500"
      :class="{
        'border-red-500 dark:border-red-600': error,
        'border-gray-300 dark:border-gray-700': !error
      }"
    />
    <p v-if="error" class="mt-1 text-sm text-red-600 dark:text-red-400">
      {{ error }}
    </p>
    <p v-else class="mt-1 text-xs text-gray-500 dark:text-gray-500">
      Must be a valid C identifier starting with "scene_" (e.g., scene_forest_entrance)
    </p>
  </div>
</template>

<script setup>
import { ref, watch } from 'vue';

const props = defineProps({
  modelValue: {
    type: String,
    default: ''
  },
  error: {
    type: String,
    default: ''
  },
  validateOnInput: {
    type: Boolean,
    default: false
  }
});

const emit = defineEmits(['update:modelValue', 'blur']);

function handleInput(event) {
  emit('update:modelValue', event.target.value);
}

function handleBlur() {
  emit('blur');
}
</script>

// apps/cards/src/components/SceneIdInput.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  const dispatch = createEventDispatcher<{ change: { value: string; valid: boolean } }>();
  export let value: string = '';
  export let label: string = 'Scene ID';
  
  const pattern = /^[A-Za-z_][A-Za-z0-9_]*$/;
  $: valid = pattern.test(value);
  function onInput(e: Event) {
    value = (e.target as HTMLInputElement).value;
    dispatch('change', { value, valid });
  }
</script>

<label class="block text-sm font-medium text-gray-900 dark:text-white" for="scene-id-input">{label}</label>
<input id="scene-id-input" class="mt-1 w-full rounded border px-2 py-1 bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
  class:border-red-500={!valid}
  class:dark:border-red-400={!valid}
  class:border-gray-300={valid}
  class:dark:border-gray-600={valid}
  bind:value
  on:input={onInput}
  aria-invalid={!valid}
  aria-describedby="sceneid-help"
  />
<p id="sceneid-help" class="text-xs mt-1" class:text-red-600={!valid} class:dark:text-red-400={!valid} class:text-gray-500={valid} class:dark:text-gray-400={valid}>
  {#if valid}
    Must be a valid C identifier.
  {:else}
    Invalid ID. Use letters, digits, and underscores; start with letter or underscore.
  {/if}
</p>
